name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shoma/envcheck:latest
    - name: Logint to docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Publish to Docker Hub
      run: docker push shoma/envcheck:latest



# vim: set et sw=2 ts=2 syntax=yaml
